### ISSUE TITLE
First play, 2022-01-10

### ISSUE THREAD

**Issue by jongfeel** [jongfeel/RockSmith#1]
Play at lunch time!

https://youtu.be/LzIBwypEnak

**Comment by KangHyeonSeok** [comment]
튜닝이 하나도 안맞아서 음악같지도 않은데 녹화 하시다니! 사진으로 만족해 주세요~
같이 하니 더 재밌네요!

**Comment by jongfeel** [comment]
ㅋㅋㅋㅋ
이제 계속 올릴겁니다
오늘은 the beginning 느낌으로

**Comment by jongfeel** [comment]
First
https://youtu.be/Jw8VYLItdFE

**Comment by jongfeel** [comment]
Second
https://youtu.be/G-bruAkdThE
