### ISSUE TITLE
락스미스 곡 구매

### ISSUE THREAD

**Issue by KangHyeonSeok** [jongfeel/RockSmith#4]
제 락스미스에 종필님 맘에 드시는 곡이 별로 없는것 같으니 아래 링크 보시고 맘에 드는 곡이 있으시면 댓글 주세요!
할인할때를 노려 구매 해봐야 겠습니다.

https://en.m.wikipedia.org/wiki/List_of_downloadable_songs_for_Rocksmith

**Comment by jongfeel** [comment]
Radiohead, No surprise.

엄청난 명곡입니다. 15년 전 쯤에 세달 내내 이 노래만 들었던거 같아요.
https://youtu.be/kePMa_cdI1E

유튜브 보시고 할만하다 싶으시면 구매 안하셔도 될 거 같군요.
